PROJECT_NAME=SAVIME

SHM_STORAGE_DIR=/dev/shm/savime
SEC_STORAGE_DIR=/dev/shm/savime
MAX_THREADS=4

HOST_SAVIME_PORT=65000
HOST_SHM_STORAGE_DIR=/dev/shm/savime
HOST_SEC_STORAGE_DIR=/dev/shm/savime

DETACH_CONTAINER_FROM_TERMINAL=true

export PROJECT_NAME
export SHM_STORAGE_DIR
export SEC_STORAGE_DIR
export MAX_THREADS
export HOST_SAVIME_PORT
export HOST_SHM_STORAGE_DIR
export HOST_SEC_STORAGE_DIR

export DETACH_CONTAINER_FROM_TERMINAL